AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1
  Exclude:
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 50

Style/ClassAndModuleChildren:
  Enabled: false
