default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: dnd_test

development:
  <<: *default
  database: dnd_development

production:
  <<: *default
  database: dnd_production
