default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dnd_development

test:
  <<: *default
  database: dnd_test

production:
  <<: *default
  database: dnd_production
  username: dnd
  password: <%= ENV['DND_DATABASE_PASSWORD'] %>
